# Generated by Django 5.0 on 2023-12-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sample',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
