# Generated by Django 5.0 on 2023-12-21 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_product_sample'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sample',
        ),
    ]
